language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
install:
  - composer install
script:
  - php ./test.php
  - ./vendor/bin/phpunit -v --debug --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
